pipeline {
    agent any
        environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }
    stages {
        stage("Checkout") {
            steps {
                dir("EC2-Instance") {
                    git branch: 'main',
                        url: 'https://github.com/RakshithaUmesh1/Terraform_Projects.git'
                }
            }
        }

        stage("Terraform Init and Validate") {
            steps {
                dir("EC2-Instance/EC2-Instance") {
                    sh 'terraform init'
                    sh 'terraform validate'
                }
            }
        }

        stage("Terraform Plan") {
            steps {
                dir("EC2-Instance/EC2-Instance") {
                    sh 'terraform plan'
                }
            }
        }

        stage("Terraform Apply") {
            steps {
                dir("EC2-Instance/EC2-Instance") {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}
